### ISSUE TITLE
Issue: Show link to discussion topic

### ISSUE THREAD

**Issue by novotnyr** [casopisdrakkar/oar#25]
Show links to discussion topic. This data is available under "Discussion" key in article metadata and is already present in the database.

**Comment by ghost** [comment]
Only 31 have discussion present, newest from issue 13. Is there going to be more use of this feature in the future? Are the metadata wrong, or don't newer articles have discussions?

**Comment by novotnyr** [comment]
Discussion hyperlinks are missing. Some of them are present in the early 
issues, but the rest must be manually consulted with RPGForum boards.

**Comment by ghost** [comment]
Done. However, it works only for a few articles that have the discussion metadata tag.
