### ISSUE TITLE
Bug: Rendering of issue 47 on homepage looks broken

### ISSUE THREAD

**Issue by ghost** [casopisdrakkar/oar#29]
As may be seen in screenshot, 
<img width="1224" alt="drakkarbug" src="https://cloud.githubusercontent.com/assets/1448913/10133439/831021bc-65dd-11e5-81b8-95e6083e7ca0.png">
rendering of issue 47 seems kinda wonky. Is there article missing or something?

**Comment by ghost** [comment]
Nevermind, that's "fulltext symbol." Most issues have just the first article being full text one, so it kind of looks like fancy beginning of the list symbol.

I'll leave this open to discuss whether we shouldn't explain what it means, somewhere.

**Comment by novotnyr** [comment]
Drakkar 47 is one of the few issues that have all articles in fulltext. Suggestions for fulltext articles are welcome, but it is hard for me to create something different than underlining or italics. 

One of the ideas is to move the fulltext guillemot after the title.

**Comment by ghost** [comment]
I think it of clashes with the pipe symbol separating articles. I tried it without the symbol, just by color, and I think it looks okay?

**Comment by novotnyr** [comment]
Please send a screenshot.

**Comment by ghost** [comment]
<img width="1213" alt="drakkarcolor" src="https://cloud.githubusercontent.com/assets/1448913/10136430/cb7eba64-65f4-11e5-9808-779eaa2c0fa5.png">

**Comment by novotnyr** [comment]
Removed guillemots and toned down the grey hyperlinks should streamline the design.
