### ISSUE TITLE
User story: Author list

### ISSUE THREAD

**Issue by ghost** [casopisdrakkar/oar#5]
I should be able to click on author's name to be able to go to articles written by that author. There should also be list of all authors accessible from the main page.

**Comment by wrb** [comment]
Solution idea: make "canonical author name" (basic ascii) method and use it as <a name="blah"> in author list and as <a href="author list#blah"> in articles and issues.

**Comment by ghost** [comment]
I added links, but author list still needs styling.

**Comment by ghost** [comment]
I would suggest different rendering for articles in author and tag list (Issue #6) - I think something that looks like article list inside issue would work with author name, and then vertical list of articles. Something like this:

> ## Author
> - Article 1 (# 2, text, pdf) 
> - Article 2 (# 47, pdf)

with 
- "# number" being link to issue in which the article was published, 
- "text" being link to full text on page (if there is one), and 
- "pdf" being link to pdf issue that includes the article.

(there should be no space between # and number, but github keeps thinking this is issue).

I would suggest either cycle colors in author/tag list, do them randomly or do something cool with them (map first letter to color or something like that)
